chore: wip

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -736,31 +736,34 @@ case "$command" in
 
   rebuild)
       if [ "$(git symbolic-ref --short HEAD)" == "master" ]; then
-        echo "Ensuring launcher is up to date"
-
-        git remote update
-
-        LOCAL=$(git rev-parse HEAD)
-        REMOTE=$(git rev-parse @{u})
-        BASE=$(git merge-base HEAD @{u})
-
-        if [ $LOCAL = $REMOTE ]; then
-          echo "Launcher is up-to-date"
-
-        elif [ $LOCAL = $BASE ]; then
-          echo "Updating Launcher..."
-          git pull || (echo 'failed to update' && exit 1)
-
-          echo "Launcher updated, restarting..."
-          exec "$0" "${SAVED_ARGV[@]}"
-
-        elif [ $REMOTE = $BASE ]; then
-          echo "Your version of Launcher is ahead of origin"
-
-        else
-          echo "Launcher has diverged source, this is only expected in Dev mode"
-        fi
-
+        echo "TODO Ensuring launcher is up to date"
+        echo "TODO Ensuring launcher is up to date"
+        echo "TODO Ensuring launcher is up to date"
+        echo "TODO Ensuring launcher is up to date"
+        echo ""
+#        git remote update
+#
+#        LOCAL=$(git rev-parse HEAD)
+#        REMOTE=$(git rev-parse @{u})
+#        BASE=$(git merge-base HEAD @{u})
+#
+#        if [ $LOCAL = $REMOTE ]; then
+#          echo "Launcher is up-to-date"
+#
+#        elif [ $LOCAL = $BASE ]; then
+#          echo "Updating Launcher..."
+#          git pull || (echo 'failed to update' && exit 1)
+#
+#          echo "Launcher updated, restarting..."
+#          exec "$0" "${SAVED_ARGV[@]}"
+#
+#        elif [ $REMOTE = $BASE ]; then
+#          echo "Your version of Launcher is ahead of origin"
+#
+#        else
+#          echo "Launcher has diverged source, this is only expected in Dev mode"
+#        fi
+#
       fi
 
       set_existing_container
